# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sqlproject.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sqlproject(object):
    def setupUi(self, sqlproject):
        sqlproject.setObjectName("sqlproject")
        sqlproject.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(sqlproject)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 141, 20))
        self.label_5.setObjectName("label_5")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(310, 380, 100, 32))
        self.button2.setObjectName("button2")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setEnabled(True)
        self.table.setGeometry(QtCore.QRect(310, 50, 481, 321))
        self.table.setRowCount(40)
        self.table.setColumnCount(5)
        self.table.setObjectName("table")
        self.table.horizontalHeader().setHighlightSections(True)
        self.table.verticalHeader().setHighlightSections(True)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 50, 127, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.line1.setObjectName("line1")
        self.verticalLayout_4.addWidget(self.line1)
        self.line2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.line2.setObjectName("line2")
        self.verticalLayout_4.addWidget(self.line2)
        self.line3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.line3.setObjectName("line3")
        self.verticalLayout_4.addWidget(self.line3)
        self.line4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.line4.setObjectName("line4")
        self.verticalLayout_4.addWidget(self.line4)
        self.button1 = QtWidgets.QPushButton(self.layoutWidget)
        self.button1.setObjectName("button1")
        self.verticalLayout_4.addWidget(self.button1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 50, 98, 111))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label1 = QtWidgets.QLabel(self.layoutWidget1)
        self.label1.setObjectName("label1")
        self.verticalLayout_5.addWidget(self.label1)
        self.label2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label2.setObjectName("label2")
        self.verticalLayout_5.addWidget(self.label2)
        self.label3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label3.setObjectName("label3")
        self.verticalLayout_5.addWidget(self.label3)
        self.label4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label4.setObjectName("label4")
        self.verticalLayout_5.addWidget(self.label4)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(420, 20, 221, 16))
        self.label_6.setObjectName("label_6")
        sqlproject.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(sqlproject)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        sqlproject.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(sqlproject)
        self.statusbar.setObjectName("statusbar")
        sqlproject.setStatusBar(self.statusbar)

        self.retranslateUi(sqlproject)
        QtCore.QMetaObject.connectSlotsByName(sqlproject)

    def retranslateUi(self, sqlproject):
        _translate = QtCore.QCoreApplication.translate
        sqlproject.setWindowTitle(_translate("sqlproject", "sqlproject"))
        self.label_5.setText(_translate("sqlproject", "CUSTOMER "))
        self.button2.setText(_translate("sqlproject", "DELETE"))
        self.button1.setText(_translate("sqlproject", "ADD"))
        self.label1.setText(_translate("sqlproject", "Name Surname:"))
        self.label2.setText(_translate("sqlproject", "Address:"))
        self.label3.setText(_translate("sqlproject", "Phone:"))
        self.label4.setText(_translate("sqlproject", "E-mail:"))
        self.label_6.setText(_translate("sqlproject", "CUSTOMER INFORMATIONS LIST"))
